FROM ubuntu:12.04
MAINTAINER Stelligent <info@stelligent.com>
RUN apt-get update
RUN apt-get install -y git
RUN git clone https://github.com/stelligent/honolulu_answers_cookbooks.git /tmp/
EXPOSE 5000